package io.constellationnetwork.metagraph_sdk.crypto.zk

import java.math.BigInteger

import io.constellationnetwork.metagraph_sdk.crypto.zk.Bn254.{G1, G2}

/**
 * Pure-JVM port of the gnark Groth16-BN254 verifier generated by SP1
 * (`Groth16Verifier.sol`, circuit version v6.1.0). The verification key is
 * hardcoded exactly as in the generated Solidity contract.
 *
 * The verifier checks the four-pairing Groth16 equation
 *
 * {{{ e(A, B) * e(C, -delta) * e(alpha, -beta) * e(L, -gamma) == 1 }}}
 *
 * where `L = CONSTANT + sum_i input_i * PUB_i` is the public-input
 * multi-scalar-multiplication (see [[publicInputMSM]]).
 *
 * ==Fp2 coordinate ordering (critical)==
 * The Solidity VK constants `BETA_NEG`, `GAMMA_NEG`, `DELTA_NEG` are stored with
 * `_0 = real` and `_1 = imag`; they are already negated. We pass them to
 * [[Bn254.G2]] as `(real, imag)` directly. In `verifyProof`'s `proof` argument
 * the G2 point B is encoded in EIP-197 order, i.e. imaginary-before-real:
 * `proof2 = Bx_imag, proof3 = Bx_real, proof4 = By_imag, proof5 = By_real`, so
 * we map it to `G2(xReal = proof3, xImag = proof2, yReal = proof5, yImag = proof4)`.
 */
object Groth16Verifier {

  // ---------------------------------------------------------------------------
  // Verification key (hardcoded, SP1 groth16 v6.1.0) -- ported verbatim from
  // Groth16Verifier.sol. G2 constants are already negated (BETA/GAMMA/DELTA).
  // _0 = real part, _1 = imaginary part.
  // ---------------------------------------------------------------------------

  private def bi(s: String): BigInteger = new BigInteger(s)

  // Groth16 alpha point in G1
  private val ALPHA_X = bi("15279411540481963483749982645131486879260751823620651493692884460296130891713")
  private val ALPHA_Y = bi("15872895802316430142046488442363778159164596024024981740547841316113839677454")

  // Groth16 beta point in G2 (negated), powers of i (_0 = real, _1 = imag)
  private val BETA_NEG_X_0 = bi("6145571844528009385227270901181311049451968424667282936975270874464890915386")
  private val BETA_NEG_X_1 = bi("12771786691609444002416405093387705070206640282801320788762089789398249455552")
  private val BETA_NEG_Y_0 = bi("4488883874756188982949192438322346627006627895205628031405236004639323835517")
  private val BETA_NEG_Y_1 = bi("1735169520034591855846686229876971881413094324547255227368057137445726296809")

  // Groth16 gamma point in G2 (negated), powers of i
  private val GAMMA_NEG_X_0 = bi("10857046999023057135944570762232829481370756359578518086990519993285655852781")
  private val GAMMA_NEG_X_1 = bi("11559732032986387107991004021392285783925812861821192530917403151452391805634")
  private val GAMMA_NEG_Y_0 = bi("13392588948715843804641432497768002650278120570034223513918757245338268106653")
  private val GAMMA_NEG_Y_1 = bi("17805874995975841540914202342111839520379459829704422454583296818431106115052")

  // Groth16 delta point in G2 (negated), powers of i
  private val DELTA_NEG_X_0 = bi("10465707362494635227101096813108413078937487707553051407465224907243675430929")
  private val DELTA_NEG_X_1 = bi("8014260607368773541998918215611927658290278403999176336697043972644519659243")
  private val DELTA_NEG_Y_0 = bi("19389283139277148919245778864125350153699493315071306268776225113374776030523")
  private val DELTA_NEG_Y_1 = bi("16335894885742905444968709132584769120387318573561090701871591658625758958113")

  // Constant and public-input points (G1)
  private val CONSTANT_X = bi("20281192269339458123687070687118212311775320590888414619062163734024177320592")
  private val CONSTANT_Y = bi("4733327396113282720944079206751955104965328647794767422434462962576999295035")
  private val PUB_0_X = bi("6933777020392885277709527453058337947310422411038083362275568070104688005311")
  private val PUB_0_Y = bi("981134475045095331624771061624185350383934842154508663637397442918499383708")
  private val PUB_1_X = bi("4994703368938944727583784298191985234033403433117347198670233075674015451426")
  private val PUB_1_Y = bi("8251219283963080431419977720140972699009004688253176317231536639169726973868")
  private val PUB_2_X = bi("4290838847096051522936899065591427041691227664160185228987863596451823131267")
  private val PUB_2_Y = bi("20588566735491008722164159313316540988426258906449040460220495569364391658476")
  private val PUB_3_X = bi("10868099250506113890234768256645470833285719586092080686774540776807380789751")
  private val PUB_3_Y = bi("481415511937576118656966359026147167555048629225366340770167496559184060449")
  private val PUB_4_X = bi("248210862999154995000539012177951057105481472135341820587821789934938975214")
  private val PUB_4_Y = bi("4435539404843896136682123140600986858809597152596796648926707165831171499457")

  private val constant: G1 = G1(CONSTANT_X, CONSTANT_Y)
  private val pubPoints: Vector[G1] = Vector(
    G1(PUB_0_X, PUB_0_Y),
    G1(PUB_1_X, PUB_1_Y),
    G1(PUB_2_X, PUB_2_Y),
    G1(PUB_3_X, PUB_3_Y),
    G1(PUB_4_X, PUB_4_Y)
  )

  // Negated VK G2 points (already negated in the constants above).
  private val betaNeg: G2 = G2(BETA_NEG_X_0, BETA_NEG_X_1, BETA_NEG_Y_0, BETA_NEG_Y_1)
  private val gammaNeg: G2 = G2(GAMMA_NEG_X_0, GAMMA_NEG_X_1, GAMMA_NEG_Y_0, GAMMA_NEG_Y_1)
  private val deltaNeg: G2 = G2(DELTA_NEG_X_0, DELTA_NEG_X_1, DELTA_NEG_Y_0, DELTA_NEG_Y_1)
  private val alpha: G1 = G1(ALPHA_X, ALPHA_Y)

  /** Number of public inputs this verifier expects. */
  val NumPublicInputs: Int = 5

  /**
   * Public-input linear combination `L = CONSTANT + sum_i input_i * PUB_i`.
   * Each input scalar must already be reduced (`< R`); unreduced scalars are
   * rejected, matching the Solidity `lt(s, R)` checks.
   */
  def publicInputMSM(input: IndexedSeq[BigInteger]): Either[String, G1] =
    if (input.length != NumPublicInputs)
      Left(s"expected $NumPublicInputs public inputs, got ${input.length}")
    else if (input.exists(s => s.signum < 0 || s.compareTo(Bn254.R) >= 0))
      Left("public input not in scalar field")
    else {
      val acc = pubPoints.indices.foldLeft(constant) { (acc, i) =>
        acc.add(pubPoints(i).multiply(input(i)))
      }
      Right(acc)
    }

  /**
   * Verify an uncompressed Groth16 proof against five public inputs.
   *
   * @param proof eight field elements `(A.x, A.y, B.x_imag, B.x_real,
   *              B.y_imag, B.y_real, C.x, C.y)` in EIP-197 order (the layout
   *              produced by gnark / abi-encoded SP1 proofs).
   * @param input five public-input scalars (elements of Fr).
   * @return `Right(())` if the proof is valid, `Left(reason)` otherwise.
   */
  def verifyProof(proof: IndexedSeq[BigInteger], input: IndexedSeq[BigInteger]): Either[String, Unit] =
    if (proof.length != 8) Left(s"expected 8 proof elements, got ${proof.length}")
    else
      publicInputMSM(input).flatMap { l =>
        val a = G1(proof(0), proof(1))
        // EIP-197 order in `proof`: imag before real.
        val b = G2(
          xReal = proof(3),
          xImag = proof(2),
          yReal = proof(5),
          yImag = proof(4)
        )
        val c = G1(proof(6), proof(7))

        // e(A, B) * e(C, -delta) * e(alpha, -beta) * e(L, -gamma) == 1
        val ok = Bn254.pairingProductIsOne(
          Seq(
            a     -> b,
            c     -> deltaNeg,
            alpha -> betaNeg,
            l     -> gammaNeg
          )
        )
        if (ok) Right(()) else Left("pairing check failed")
      }
}
